bisect – roots-fortran
bisect Function
6 statements
Source File
private pure function bisect(x1, x2) result(x3)
Bisection step.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x1
real(kind=wp), intent(in) :: x2
Return Value real(kind=wp)
point half way between x1 and x2
Called by
Source Code
    pure function bisect(x1,x2) result(x3)
    implicit none
    real(wp),intent(in) :: x1,x2
    real(wp) :: x3 !! point half way between x1 and x2
    x3 = (x1 + x2) / 2.0_wp
    end function bisect
Call graph
anderson_bjorck_kroger calls bisect, secant
bdqrf calls bisect
bisection calls bisect
itp calls bisect
modab calls bisect, regula_falsi_step
muller calls bisect
parabolic calls bisect
rbp calls bisect, parabolic, regula_falsi_step
regula_falsi_step calls bisect
ridders calls bisect
secant calls bisect
zhang calls bisect, secant
anderson_bjorck calls secant
illinois calls regula_falsi_step
pegasus calls secant
regula_falsi calls regula_falsi_step