choose_best – roots-fortran
choose_best Subroutine
14 statements
Source File
private pure subroutine choose_best(x1, x2, f1, f2, xbest, fbest)
Given two points with two function evaluations, choose the best one (the one closest to the root).
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x1
real(kind=wp), intent(in) :: x2
real(kind=wp), intent(in) :: f1
real(kind=wp), intent(in) :: f2
real(kind=wp), intent(out) :: xbest
real(kind=wp), intent(out) :: fbest
Called by
Source Code
    pure subroutine choose_best(x1,x2,f1,f2,xbest,fbest)
    implicit none
    real(wp),intent(in) :: x1,x2
    real(wp),intent(in) :: f1,f2
    real(wp),intent(out) :: xbest
    real(wp),intent(out) :: fbest
    if (abs(f1)<abs(f2)) then
        xbest = x1
        fbest = f1
    else
        xbest = x2
        fbest = f2
    end if
    end subroutine choose_best
Call graph
anderson_bjorck calls choose_best
anderson_bjorck_kroger calls choose_best
barycentric calls choose_best
bdqrf calls choose_best
bisection calls choose_best
blendtf calls choose_best
illinois calls choose_best
itp calls choose_best
muller calls choose_best
pegasus calls choose_best
regula_falsi calls choose_best
zhang calls choose_best