converged – roots-fortran
converged Function
18 statements
Source File
private pure function converged(me, a, b)
Determines convergence in x based on if the reltol or abstol is satisfied.
Type Bound
root_solver
Arguments
Type Intent Optional Attributes Name
class(root_solver), intent(in) :: me
real(kind=wp), intent(in) :: a
old value
real(kind=wp), intent(in) :: b
new value
Return Value logical
Called by
Source Code
    pure function converged(me,a,b)
    implicit none
    class(root_solver),intent(in) :: me
    real(wp),intent(in) :: a !! old value
    real(wp),intent(in) :: b !! new value
    logical :: converged
    real(wp) :: d
    ! original way:
    ! converged = (abs(b-a) <= abs(b)*me%rtol + me%atol) exit
    d = abs(b-a)
    if (d <= me%atol) then
        ! absolute
        converged = .true.
    else
        ! relative
        if (a /= 0.0_wp) then
            converged = d / abs(a) <= me%rtol
        else
            converged = .false.
        end if
    end if
    end function converged
Call graph
anderson_bjorck calls converged
anderson_bjorck_kroger calls converged
barycentric calls converged
bdqrf calls converged
bisection calls converged
blendtf calls converged
illinois calls converged
itp calls converged
modab calls converged
muller calls converged
pegasus calls converged
rbp calls converged
regula_falsi calls converged
ridders calls converged
zhang calls converged