initialize_root_solver – roots-fortran
initialize_root_solver Subroutine
14 statements
Source File
private subroutine initialize_root_solver(me, f, ftol, rtol, atol, maxiter)
Initialize the root_solver class.
Note that all optional inputs are not used for all methods.
Type Bound
root_solver
Arguments
Type Intent Optional Attributes Name
class(root_solver), intent(out) :: me
procedure(func) :: f
user function f(x) to find the root of
real(kind=wp), intent(in), optional :: ftol
absolute tolerance for f=0
real(kind=wp), intent(in), optional :: rtol
relative tol for x
real(kind=wp), intent(in), optional :: atol
absolute tol for x
integer, intent(in), optional :: maxiter
maximum number of iterations
Called by
Source Code
    subroutine initialize_root_solver(me,f,ftol,rtol,atol,maxiter)
    implicit none
    class(root_solver),intent(out) :: me
    procedure(func)               :: f        !! user function `f(x)` to find the root of
    real(wp),intent(in),optional  :: ftol     !! absolute tolerance for `f=0`
    real(wp),intent(in),optional  :: rtol     !! relative tol for x
    real(wp),intent(in),optional  :: atol     !! absolute tol for x
    integer,intent(in),optional   :: maxiter  !! maximum number of iterations
    me%f => f
    if (present(ftol))    me%ftol    = abs(ftol)
    if (present(rtol))    me%rtol    = abs(rtol)
    if (present(atol))    me%atol    = abs(atol)
    if (present(maxiter)) me%maxiter = abs(maxiter)
    end subroutine initialize_root_solver
Call graph
root_scalar_by_type calls initialize_root_solver, solve
root_scalar calls root_scalar_by_type, root_scalar_by_name
root_scalar_by_name calls root_scalar
solve calls root_scalar