lowercase – roots-fortran
lowercase Function
14 statements
Source File
private pure function lowercase(str) result(s_lower)
lowercase a string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
input string
Return Value character(len=len=(len(str)))
lowercase version of the string
Called by
Source Code
    pure function lowercase(str) result(s_lower)
    implicit none
    character(len=*),intent(in) :: str      !! input string
    character(len=(len(str)))   :: s_lower  !! lowercase version of the string
    integer :: i  !! counter
    integer :: j  !! index of uppercase character
    character(len=*),parameter :: upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' !! uppercase characters
    character(len=*),parameter :: lower = 'abcdefghijklmnopqrstuvwxyz' !! lowercase characters
    s_lower = str
    do i = 1, len_trim(str)
        j = index(upper,s_lower(i:i))
        if (j>0) s_lower(i:i) = lower(j:j)
    end do
    end function lowercase
Call graph
root_name_to_method calls lowercase
root_scalar_by_name calls root_name_to_method, root_scalar
root_scalar calls root_scalar_by_name, root_scalar_by_type
solve calls root_scalar
root_scalar_by_type calls solve