solution – roots-fortran
solution Function
15 statements
Source File
private function solution(me, x, f, xzero, fzero)
Returns true if this is a solution and sets xzero and fzero.
Type Bound
root_solver
Arguments
Type Intent Optional Attributes Name
class(root_solver), intent(inout) :: me
real(kind=wp), intent(in) :: x
real(kind=wp), intent(in) :: f
real(kind=wp), intent(inout) :: xzero
real(kind=wp), intent(inout) :: fzero
Return Value logical
Called by
Source Code
    logical function solution(me,x,f,xzero,fzero)
    implicit none
    class(root_solver),intent(inout) :: me
    real(wp),intent(in) :: x
    real(wp),intent(in) :: f
    real(wp),intent(inout) :: xzero
    real(wp),intent(inout) :: fzero
    if (abs(f) <= me%ftol) then
        xzero = x
        fzero = f
        solution = .true.
    else
        solution = .false.
    end if
    end function solution
Call graph
anderson_bjorck calls solution
anderson_bjorck_kroger calls solution
barycentric calls solution
bdqrf calls solution
bisection calls solution
blendtf calls solution
chandrupatla calls solution
illinois calls solution
itp calls solution
modab calls solution
muller calls solution
pegasus calls solution
rbp calls solution
regula_falsi calls solution
ridders calls solution
solve calls solution, root_scalar
zhang calls solution
root_scalar_by_type calls solve
root_scalar calls root_scalar_by_type, root_scalar_by_name
root_scalar_by_name calls root_scalar